version: '3.8'

services:
  backend:
    build: ./backend
    container_name: zapping-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_secret_key_change_in_production

volumes:
  sqlite_data: